research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}. Include source URLs for each piece of information.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic} and code exemples
    if applicable. Each bullet point should be a single sentence, followed by its source URL in 
    [reference format]. The information should be up to date and relevant to the current year.
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
    Include source references at the end of each section.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Each section should end with a "Fonte:" followed by the reference links from the research.
    Formatted as markdown without '```' code blocks and translate to brazilian portuguese.
  agent: reporting_analyst
